import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts", "styles.sass"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: ".",
  loader: {
    '.sass': 'css'
  },
  plugins: [
    {
      name: 'sass',
      setup(build) {
        build.onResolve({ filter: /\.sass$/ }, args => ({
          path: args.path,
          namespace: 'sass'
        }))
      }
    }
  ]
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
} 