import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const targetDir = 'C:\\Users\\Wonvy\\Desktop\\小顽\\笔记\\.obsidian\\plugins\\obsidian-card-view';

// 复制文件到目标目录
const copyToTarget = () => {
    ['main.js', 'styles.css', 'manifest.json'].forEach(file => {
        fs.copyFileSync(
            path.join(process.cwd(), file),
            path.join(targetDir, file)
        );
    });
    console.log('文件已复制到:', targetDir);
};

const config = {
    banner: {
        js: banner,
    },
    entryPoints: ['main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins
    ],
    format: 'cjs',
    watch: !prod && {
        onRebuild(error) {
            if (error) console.error('构建失败:', error);
            else {
                console.log('构建成功');
                copyToTarget();
            }
        },
    },
    target: 'es2018',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
};

try {
    await esbuild.build(config);
    if (!prod) {
        console.log("监视构建中...");
    } else {
        copyToTarget();
    }
} catch (err) {
    console.error(err);
    process.exit(1);
} 